var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/leads/[id]/move/route.js")
R.c("server/chunks/_1m8giy2._.js")
R.c("server/chunks/[root-of-the-server]__0dp40is._.js")
R.c("server/chunks/lib_14wf3ii._.js")
R.c("server/chunks/lib_i18n_dicionario_ts_1w6f_qz._.js")
R.c("server/chunks/lib_0t7vm99._.js")
R.c("server/chunks/lib_0jf1qa7._.js")
R.c("server/chunks/_07w9zvr._.js")
R.c("server/chunks/_211ebc6._.js")
R.c("server/chunks/1bq-_@supabase_supabase-js_dist_index_mjs_1s-h-q3._.js")
R.c("server/chunks/[root-of-the-server]__1flnvgd._.js")
R.c("server/chunks/1_zl_next_dist_1mniuaq._.js")
R.c("server/chunks/1_zl_next_0un6vjm._.js")
R.c("server/chunks/0sj1_@opentelemetry_api_build_esm_0mlz9i_._.js")
R.c("server/chunks/_1_hvvyi._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_leads_[id]_move_route_actions_0xhfpz4.js")
R.m(492913)
module.exports=R.m(492913).exports
